apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aws-actions-connector
spec:
  package: ghcr.io/hops-ops/aws-actions-connector:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}

---

# skipDependencyResolution false would name this hops-ops-aws-actions-connectorrender
# so we need to match that format to avoid issues with the package name
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-aws-actions-connectorrender
spec:
  package: ghcr.io/hops-ops/aws-actions-connector_render:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}
